### ISSUE TITLE
article gpio

### ISSUE THREAD

**Issue by tarekziade** [faitmain/faitmain.org#16]
@fdion je mets quelques retours de lecture:

1/ dans la section Python on utilise le module RPi sans le présenter - je pense qu'il faut l'introduire et expliquer comment l'installer - ou fournir un lien vers ces explications la

2/ termes qui peuvent avoir un lien wikipedia: GPIO, DEL

3/ Control-C vs CTRL-C

**Comment by tarekziade** [comment]
todo: inserer l;article dans l'edito + page auteur

**Comment by fdion** [comment]
j'ai corrige 1 a 3 et reduit les images

**Comment by tarekziade** [comment]
merci!
