### ISSUE TITLE
CSS fix moves everything on the left

### ISSUE THREAD

**Issue by tarekziade** [faitmain/faitmain.org#2]
the fix altered the centering of the text body. It's now not properly centered (the search and social is a right toobar)

X != Y =!= Z here, we should have X == Z

![Screen Shot 2013-01-14 at 1 20 26 PM](https://f.cloud.github.com/assets/250019/64400/5b4172be-5e45-11e2-8c85-a4df41ff955a.png)

**Comment by tarekziade** [comment]
I've done something that seems good enough: raised to 1000px the max-width. can you check on your big screen how it looks @Exirel  ?

**Comment by Exirel** [comment]
I am not bothered by a content left-aligned, so as the content does not spread all over wide-screens, 800 or 1000px sound good enough (I just try, it looks good).
Now if anyone complains, I will create a "wide-screen.css" with a media-query for wide-screen. ;-)
