### ISSUE TITLE
map des fablabs

### ISSUE THREAD

**Issue by tarekziade** [faitmain/faitmain.org#83]
faire une carte des fablabs sur 

http://fablabs.faimain.org 

avec une manière simple d'en ajouter

voir:  http://coinmap.org/

**Comment by mere-teresa** [comment]
Super idée :+1:

**Comment by tarekziade** [comment]
hop:
- prototype en ligne http://fablab.faitmain.org/
- repo: https://github.com/faitmain/fablab.faitmain.org
